### ISSUE TITLE
default boolean value fails

### ISSUE THREAD

**Issue by doudou** [peter-murach/tty#17]
I tried to set up a simple yes/no question with a default of 'yes' and get an error when I simply press enter.

Running

```
TTY::Shell.new.ask 'So, yes or no ?' do
  default 'yes'
end.read_bool
```

and pressing ENTER on the prompt leads to

```
[1] pry(main)> TTY::Shell.new.ask 'So, yes or no ?' do
[1] pry(main)*   default 'yes'  
[1] pry(main)* end.read_bool  
So, yes or no ?

Necromancer::ConversionTypeError: '
' could not be converted from `string` into `boolean` 
from /home/doudou/dev/flat_fish/.gems/gems/necromancer-0.3.0/lib/necromancer/converter.rb:48:in `fail_conversion_type'
```

(Note: the newline between the two quotes just after ConvertionTypeError is not a formatting glitch, it is displayed as-is on the terminal)

It seems that Question#evaluate_response expects 'nil' as 'no answer' but gets a newline character. Weirdly enough, if I do read_string, I get an empty string (no more newline)

**Comment by peter-murach** [comment]
Hi Sylvain,

The whole tty library is undergoing changes which involve extracting components. I've managed to extract quite few so far such as [tty-progressbar](https://github.com/peter-murach/tty-progressbar) . 

The interface for asking for user input quite frankly lacks robustness and hasn't been maintained for some time. In near future I would like to change this situation and extract is as it's own independent component with more robust architecture.

Considering the current bug that you found, if you have time I would really appreciate contribution. On my part, I cannot say when this will be fixed as I'm currently taking a small sabbatical(few weeks) to rethink and refresh my open source enthusiasm. However, I'm still happy to merge patches and release new version. Let me have your thoughts?

**Comment by doudou** [comment]
Hi Peter

I'll try to find the problem and patch it, but I unfortunately have little time right now so don't hold your breath :( Wanted to try TTY out, it's a really really nice looking library for everything console related.

Can you share a little bit more on your future plans ? Would really hate to migrate to TTY to find out that everything changed ;-) Right now, I'm mostly using the tables and pastel.

Sylvain

**Comment by doudou** [comment]
OK ... so allocated 15 mins to check it out ... https://github.com/peter-murach/tty/pull/18

One question: what does the harcoded 10 at https://github.com/peter-murach/tty/blob/master/lib/tty/shell/response.rb#L60 imply ? Does it mean that the answer cannot be more than 10 characters long ?

**Comment by doudou** [comment]
Aaannnnnddddd. Run tests before submitting anything. facepalm /me. Will fix ASAP.

**Comment by doudou** [comment]
See #19. Tests still not fully passing, but this time it's on purpose (I'd like to have your opinion on the fix)

**Comment by peter-murach** [comment]
`tty` in the past grew into a large and flaky codebase, it was much harder to ensure quality and decent interface. Rewind to today, much more robust individual components on a sure path to 1.0 release with simple internals as well as external api backed by full coverage. To answer your question, the components already extracted will not change but only get bug fixes and new features. There are few remaining components to be extracted and new added. One of them is the interface for prompting user input. I have no intention of changing how it works but to follow the above philosophy as well as make the component the best it can be and thus I will extract it to another dependency `tty-...`. In my plans i want to extend public api to allow for presenting lists to user that get checkmark when done/selected, checkboxes and other more fancy inputs! I want to offer fancy menu choices for user to select from by using terminal navigation etc... This part got neglected for too long and I want to bring it up to speed. Does that answer your query?

**Comment by doudou** [comment]
> Does that answer your query?

Definitely does. Thanks for taking the time to answer it so thoroughly ;-)
