### ISSUE TITLE
undefined method `header'

### ISSUE THREAD

**Issue by gferguson-gd** [peter-murach/tty#7]
In IRB, if I run this example from the documentation:

    table = TTY::Table[['a1', 'a2'], ['b1', 'b2']]

I get:

    NoMethodError: undefined method `header' for #<Object:0x007ffc110e1568>
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/tty-0.1.0/lib/tty/support/equatable.rb:90:in `block (2 levels) in define_compare'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/tty-0.1.0/lib/tty/support/equatable.rb:90:in `each'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/tty-0.1.0/lib/tty/support/equatable.rb:90:in `all?'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/tty-0.1.0/lib/tty/support/equatable.rb:90:in `block in define_compare'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/tty-0.1.0/lib/tty/support/equatable.rb:146:in `=='
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/formatter.rb:66:in `awesome_self'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/formatter.rb:28:in `format'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/inspector.rb:137:in `unnested'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/inspector.rb:104:in `awesome'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
      from /Users/gferguson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/awesome_print-1.2.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
      from /Users/gferguson/.irbrc:33:in `output_value'
      from /Users/gferguson/.rbenv/versions/2.1.3/bin/irb:11:in `<main>'

**Comment by peter-murach** [comment]
@gferguson-gd - sorry, completely missed that one!

You are correct, the hash like initialisation doesn't work, however you can still use the library like so:
 
```ruby
table = TTY::Table.new [['a1', 'a2'], ['b1', 'b2']]

puts table.to_s
```
I am going to extract table creation to it's own dependency and leave this ticket open for reference and let you know when this is fixed. I intend to provide better maintenance for this library and welcome any feedback and contributions!

**Comment by peter-murach** [comment]
Fixed in [tty-table](https://github.com/peter-murach/tty-table)
