### ISSUE TITLE
Can't display utf-8 correctory 

### ISSUE THREAD

**Issue by mattn** [peter-murach/tty#9]
![](http://go-gyazo.appspot.com/bd01ae1156e44c0e.png)

String size is not string width.

**Comment by peter-murach** [comment]
Table rendering has been moved out of `tty` to its own repository https://github.com/peter-murach/tty-table  - the unicode content has been fixed on master branch https://github.com/peter-murach/tty-table/commit/780db8da21dc4b74f2f3e1fe63d8ce51c42594af

**Comment by mattn** [comment]
I made sure the fixing. Thanks.

**Comment by peter-murach** [comment]
@mattn　これわたいへんしゅうせいでした。それがこのするよになりました、ぼくわうれしいです。ありがとう！
